[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
link-args = [ "-Wl,--sysroot=/usr/aarch64-linux-gnu", "-L/usr/aarch64-linux-gnu/lib" ]

[build]
target = "aarch64-unknown-linux-gnu"
